### ISSUE TITLE
Declare Reuse code/section

### ISSUE THREAD

**Issue by DennieDan** [AY2425S1-CS2103T-F14a-1/tp#313]
Refer to the [course website](https://nus-cs2103-ay2425s1.github.io/website/schedule/week12/admin.html#policy-on-reuse) for how we can declare Reused code/sections in documentation (if applicable)

**Comment by Feng1231** [comment]
[//]: # (First three paragraphs below inspired by https://ay2324s1-cs2103t-t08-2.github.io/tp/DeveloperGuide.html#add-details)
