### ISSUE TITLE
[PE-D][Tester B] Find command unclear error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-1/tp#314]
![find-unclear-errormsg.png](https://raw.githubusercontent.com/SQ77/ped/main/files/363840c5-48bf-44b1-8001-69f0612c567b.png)

The error message should state that the input contains commas, which are not allowed in the parameter d/

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: SQ77/ped#1

**Comment by Soumyadip-cmd** [comment]
Clarify in forum if error message can be changed
