### ISSUE TITLE
[PE-D][Tester C] Overlapping time schedules creates confusion 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-1/tp#323]
![image.png](https://raw.githubusercontent.com/YangQF2002/ped/main/files/3a036d94-11e9-4030-be90-affb448f5432.png)

This is not technically wrong, as could be on different dates 
However, since the date is not provided, the tutor have no idea which student comes first and which student comes next,  so it hinders the user experience of the tutor abit 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: YangQF2002/ped#1

**Comment by Soumyadip-cmd** [comment]
Unclear and maybe invalid
