### ISSUE TITLE
[PE-D][Tester E] Duplicate email is allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-1/tp#356]
![Screenshot 2024-11-08 at 5.24.57 PM.png](https://raw.githubusercontent.com/seantham21/ped/main/files/56c74f88-90ed-4720-9cd3-e99c35f012cd.png)

Should the user be allowed to add tutees with the same email?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: seantham21/ped#14

**Comment by DennieDan** [comment]
UG: Explain why SAME NAME + SAME PHONE not allowed but SAME NAME + SAME other things are allowed
