### ISSUE TITLE
[PE-D][Tester B] UI image in UG not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-1/tp#381]
![ui-not-updated.png](https://raw.githubusercontent.com/SQ77/ped/main/files/8abd265e-52c4-4bf1-946a-800d4d4794f3.png)

The above UI image in the UG shows the storage file being named as `addressbook.json`, but the actual app has the storage file named as `ugteach.json`.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SQ77/ped#15

**Comment by DennieDan** [comment]
We will change the UI. Thanks a lot
