### ISSUE TITLE
Update Person UI to display schedule, subject, rate, paid, owedAmount

### ISSUE THREAD

**Issue by TY1Fan** [AY2425S1-CS2103T-F14a-1/tp#65]
![Screenshot 2024-10-14 233307](https://github.com/user-attachments/assets/19be0b7c-99ac-473a-9665-2d3cd04aa9d3)

Updated Person UI

**Comment by Feng1231** [comment]
It should look like this:
![image](https://github.com/user-attachments/assets/5c3da13a-3c13-48ae-b8d4-4b36cc5392a5)

**Comment by teamotitan** [comment]
I apologize for my mistake. Thank you for your suggestion and I will make the relevant changes!

**Comment by teamotitan** [comment]
![image](https://github.com/user-attachments/assets/2e5a41f1-409c-43de-9281-e72d2bbe6d1d)

Updated Ui
